### PR TITLE
AST nodes - improve equals implementation and avoid mutability

### PR DESCRIPTION
**Pull request by MikkCZ**
Hi @Pike .

I expect this is still in some early, more experimental phase, however I decided to read through the code. When doing so, I think it would be nice to improve some of the constructions as I read them, which also helps me to understand what the code actually does.

I started with the AST nodes. For them I would propose two changes implemented in this PR - equals method without mutable intermittent structures, and avoiding mutability of the nodes in general.

### CODE REVIEW

**Comment by MikkCZ** [comment]
If you are at least semi-happy with these changes, I will continue reading through the code and hopefully help you implement something too, when I know what's where.

**Comment by Pike** [comment]
Heyhey ;-)

I'll gladly take input on better practices on Kotlin code, I'm such a rookie.

The first patch looks nice, I had only a cursory glance at companions so far, and ditched that bullet. There's a linting question, though. I've started using `ktlint --disabled_rules=no-wildcard-imports`, though I haven't documented or automated that :-/ . Also, I have no idea if that's a good practice or not.

For the second patch, I'm not so fond on the constness. This implementation is really tailored for localization tooling, and I think that at least at some level, being able to modify inline is a great plus. At least at the Resource level, and I'd argue at the Message level, too. I'd really like to have more experience on practical uses before restricting mutability.

Do you want to split this up into two PRs?

**Comment by MikkCZ** [comment]
Hi.

I am also not a Kotlin veteran, most of my experience comes from Java and from what Java lacks and Kotlin gives me. As for `klint`, I have no experience with that tool, I never linted Java nor Kotlin code this way. I usually use PMD + Spotbugs for Java, and IntelliJ hints for the code formatting etc.

No problem. I will gladly split that into two PRs.

**Comment by MikkCZ** [comment]
Note for the mutability, the more immutable usually data object go, the less there are race conditions etc., and more importantly less `null`s (long live all NullPointerExceptions I ever produced so far). ;)

**Comment by Pike** [comment]
Side note, I'm hoping that race conditions etc are a thing of a runtime implementation more than syntax tooling.

And for runtime, I encourage to use/build/fix up https://github.com/JohnnyJayJay/javidaloca.

**Pull request closed without merging**
